### PR TITLE
Allow path to accept a parent directory

### PR DESCRIPTION
**Pull request by tdorsey**
refs hjanuschka/fastlane-plugin-update_project_codesigning#1

Not entirely sure this will solve it, I don't know ruby well enough to say.

### CODE REVIEW

**Comment by hjanuschka** [comment]
seems to be good - thx for your contribution

**Comment by DBocksteger** [comment]
Having a similar problem. This is my directory structure:
bildschirmfoto 2016-10-15 um 22 39 57

So I've added the following lane to update this (and additional) settings.

```
    desc "Deploy a new version to the App Store"
    lane :codesign do

        cert
        sigh

        update_project_codesigning(path: "../ToWoo.xcodeproj", use_automatic_signing: false)
        update_provisioning_profile_specifier(project: "../ToWoo.xcodeproj", prov_name: "AppStore_com.dbocksteger.ToWoo.mobileprovision")
    end
```

But running my release lane throws the following error:

```
[22:34:58]: Error setting value '../ToWoo.xcodeproj' for option 'path'
[22:34:58]: You passed invalid parameters to 'update_project_codesigning'.
[22:34:58]: Check out the error below and available options by running `fastlane action update_project_codesigning`
```

How should I pass the path to the project?

**Comment by hjanuschka** [comment]
strange - i have the exact same direcotry structure
you could try adding:

```

puts Dir.pwd

```

to the lane - to figure out where fastlane is currently :D - and than adjust the "../" - sometimes the cwd is pretty messed up

**Comment by DBocksteger** [comment]
This prints out `/Users/dbocksteger/Entwicklung/Projekte/ToWoo/iOS/fastlane` what is exactly what I've expected to be... so `../ToWoo.xcodeproj` should be working, right?

**Comment by hjanuschka** [comment]
ok pushed new gem - hopefully this fixes it. version `0.1.2`

**Comment by hjanuschka** [comment]
https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning/commit/1ee42c2c27efa10f21e8652e01daf853bc8173dc

**Comment by DBocksteger** [comment]
Currently updating **some** gems :D Getting back with result in a few minutes :-)

**Comment by DBocksteger** [comment]
@hjanuschka already failing with the same error :-(

**Comment by hjanuschka** [comment]
have you tried it without "../"

**Comment by DBocksteger** [comment]
@hjanuschka solved it :-)

**Comment by hjanuschka** [comment]
guess this is what `File.expand_path` does (still learning ruby)  :) glad you solved it!
hope the other signing issues will be resolvable too

**Pull request merged**
